"""initial schema

Revision ID: c25bff6e1243
Revises:
Create Date: 2026-07-03 16:36:39.097829
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c25bff6e1243"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genre",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("genre", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_genre_name"), ["name"], unique=True)

    op.create_table(
        "job_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("running", "success", "failed", name="runstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("stats", sa.JSON(), nullable=True),
        sa.Column("log_ref", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job_run", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_run_kind"), ["kind"], unique=False)

    op.create_table(
        "metadata_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("cache_key", sa.String(length=512), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "cache_key", name="uq_cache_key"),
    )
    with op.batch_alter_table("metadata_cache", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_metadata_cache_cache_key"), ["cache_key"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_metadata_cache_provider"), ["provider"], unique=False)

    op.create_table(
        "provider_setting",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "indexer", "subtitle", "metadata", "library", name="providerkind", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "setting",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "title",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("imdb_id", sa.String(length=16), nullable=True),
        sa.Column("tvdb_id", sa.Integer(), nullable=True),
        sa.Column(
            "kind", sa.Enum("movie", "series", name="titlekind", native_enum=False), nullable=False
        ),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("runtime", sa.Integer(), nullable=True),
        sa.Column("imdb_rating", sa.Float(), nullable=True),
        sa.Column("imdb_votes", sa.Integer(), nullable=True),
        sa.Column("tmdb_rating", sa.Float(), nullable=True),
        sa.Column("tmdb_votes", sa.Integer(), nullable=True),
        sa.Column("popularity", sa.Float(), nullable=True),
        sa.Column("poster_url", sa.String(length=1024), nullable=True),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("title", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_title_imdb_id"), ["imdb_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_title_tmdb_id"), ["tmdb_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_title_tvdb_id"), ["tvdb_id"], unique=False)

    op.create_table(
        "candidate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("discovery", "watchlist", "manual", name="candidatesource", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "approved",
                "queued",
                "downloading",
                "imported",
                "rejected",
                "failed",
                name="candidatestatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["title.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("candidate", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_candidate_title_id"), ["title_id"], unique=False)

    op.create_table(
        "owned_file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(length=2048), nullable=False),
        sa.Column(
            "kind", sa.Enum("movie", "series", name="titlekind", native_enum=False), nullable=False
        ),
        sa.Column("season", sa.Integer(), nullable=True),
        sa.Column("episode", sa.Integer(), nullable=True),
        sa.Column("resolution", sa.String(length=16), nullable=True),
        sa.Column("codec", sa.String(length=32), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("container", sa.String(length=16), nullable=True),
        sa.Column("subtitle_langs", sa.JSON(), nullable=True),
        sa.Column("file_hash", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["title.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path", name="uq_owned_file_path"),
    )
    with op.batch_alter_table("owned_file", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_owned_file_title_id"), ["title_id"], unique=False)

    op.create_table(
        "title_genre",
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column("genre_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["genre.id"],
        ),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["title.id"],
        ),
        sa.PrimaryKeyConstraint("title_id", "genre_id"),
    )
    op.create_table(
        "download",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=True),
        sa.Column("release", sa.Text(), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=True),
        sa.Column("progress", sa.Float(), nullable=True),
        sa.Column("save_path", sa.String(length=2048), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidate.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("download", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_download_candidate_id"), ["candidate_id"], unique=False
        )

    op.create_table(
        "subtitle",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column("owned_file_id", sa.Integer(), nullable=True),
        sa.Column("lang", sa.String(length=8), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("path", sa.String(length=2048), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owned_file_id"],
            ["owned_file.id"],
        ),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["title.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("subtitle", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_subtitle_title_id"), ["title_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subtitle", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subtitle_title_id"))

    op.drop_table("subtitle")
    with op.batch_alter_table("download", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_download_candidate_id"))

    op.drop_table("download")
    op.drop_table("title_genre")
    with op.batch_alter_table("owned_file", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_owned_file_title_id"))

    op.drop_table("owned_file")
    with op.batch_alter_table("candidate", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidate_title_id"))

    op.drop_table("candidate")
    with op.batch_alter_table("title", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_title_tvdb_id"))
        batch_op.drop_index(batch_op.f("ix_title_tmdb_id"))
        batch_op.drop_index(batch_op.f("ix_title_imdb_id"))

    op.drop_table("title")
    op.drop_table("setting")
    op.drop_table("provider_setting")
    with op.batch_alter_table("metadata_cache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_metadata_cache_provider"))
        batch_op.drop_index(batch_op.f("ix_metadata_cache_cache_key"))

    op.drop_table("metadata_cache")
    with op.batch_alter_table("job_run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_run_kind"))

    op.drop_table("job_run")
    with op.batch_alter_table("genre", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_genre_name"))

    op.drop_table("genre")
    # ### end Alembic commands ###
